// None of the scraped sites reliably expose a per-listing body type, so this infers one
// from the model name (and engine size, for Japan's "Kei" class) using a lookup table of
// common JDM export models. Unmapped models are left uncategorized rather than guessed.

const KEI_MAX_CC = 660;

const BODY_TYPE_BY_MODEL: Record<string, string> = {
  // Sedans
  corolla: "Sedan",
  "corolla axio": "Sedan",
  chaser: "Sedan",
  "mark ii": "Sedan",
  "mark x": "Sedan",
  crown: "Sedan",
  camry: "Sedan",
  allion: "Sedan",
  premio: "Sedan",
  belta: "Sedan",
  aristo: "Sedan",
  civic: "Sedan",
  accord: "Sedan",
  lancer: "Sedan",
  "lancer evolution": "Sedan",
  is300: "Sedan",
  skyline: "Sedan",
  impreza: "Sedan",
  "impreza wrx sti": "Sedan",
  cima: "Sedan",
  laurel: "Sedan",
  cresta: "Sedan",
  windom: "Sedan",
  celsior: "Sedan",
  century: "Sedan",
  bluebird: "Sedan",
  familia: "Sedan",
  atenza: "Sedan",
  grace: "Sedan",

  // Coupes / sports cars
  silvia: "Coupe",
  supra: "Coupe",
  celica: "Coupe",
  "rx-7": "Coupe",
  "skyline gt-r": "Coupe",
  "mr-s": "Coupe",
  "mr2": "Coupe",
  86: "Coupe",
  gr86: "Coupe",
  soarer: "Coupe",
  prelude: "Coupe",
  sera: "Coupe",
  fairlady: "Coupe",
  "lc500": "Coupe",

  // Convertibles
  s2000: "Convertible",
  roadster: "Convertible",
  "roadster (mx-5)": "Convertible",

  // SUVs
  "land cruiser": "SUV",
  "land cruiser prado": "SUV",
  "land cruiser 250": "SUV",
  "land cruiser fj": "SUV",
  "fj cruiser": "SUV",
  harrier: "SUV",
  "harrier hybrid": "SUV",
  rav4: "SUV",
  forester: "SUV",
  outback: "SUV",
  pajero: "SUV",
  "cx-5": "SUV",
  cx5: "SUV",
  "cx-3": "SUV",
  cx3: "SUV",
  "cx-30": "SUV",
  cx30: "SUV",
  "cx-7": "SUV",
  cx7: "SUV",
  vezel: "SUV",
  "x-trail": "SUV",
  xtrail: "SUV",
  outlander: "SUV",
  raize: "SUV",
  rush: "SUV",
  "cr-v": "SUV",
  crv: "SUV",
  "hilux surf": "SUV",
  kluger: "SUV",
  vanguard: "SUV",
  "c-hr": "SUV",
  chr: "SUV",
  escudo: "SUV",
  juke: "SUV",
  dualis: "SUV",
  delica: "SUV",
  rvr: "SUV",
  tribute: "SUV",
  xv: "SUV",
  "wr-v": "SUV",
  ignis: "SUV",
  "sx4": "SUV",

  // Vans / minivans
  hiace: "Van",
  "hiace van": "Van",
  "hiace wagon": "Van",
  voxy: "Van",
  noah: "Van",
  alphard: "Van",
  vellfire: "Van",
  elgrand: "Van",
  sienta: "Van",
  serena: "Van",
  odyssey: "Van",
  stepwagon: "Van",
  freed: "Van",
  liteace: "Van",
  regiusace: "Van",
  "regiusace van": "Van",
  townace: "Van",
  esquire: "Van",
  estima: "Van",
  granace: "Van",
  isis: "Van",
  spade: "Van",
  roomy: "Van",
  tank: "Van",
  vanette: "Van",
  caravan: "Van",
  bongo: "Van",
  ad: "Van",
  succeed: "Van",
  porte: "Van",
  "s-mx": "Van",
  premacy: "Van",
  biante: "Van",
  shuttle: "Van",
  coaster: "Van",
  rosa: "Van",
  nv150: "Van",
  nv200vanette: "Van",
  nv350caravan: "Van",

  // Hatchbacks
  vitz: "Hatchback",
  yaris: "Hatchback",
  aqua: "Hatchback",
  fit: "Hatchback",
  swift: "Hatchback",
  demio: "Hatchback",
  note: "Hatchback",
  march: "Hatchback",
  passo: "Hatchback",
  ractis: "Hatchback",
  probox: "Hatchback",
  auris: "Hatchback",
  "corolla sport": "Hatchback",
  "yaris cross": "Hatchback",
  mirage: "Hatchback",
  leaf: "Hatchback",
  tiida: "Hatchback",
  cube: "Hatchback",
  verisa: "Hatchback",
  trezia: "Hatchback",
  solio: "Hatchback",
  prius: "Hatchback",
  "prius α": "Wagon",
  "ct200h": "Hatchback",
  ct: "Hatchback",

  // Wagons
  "corolla fielder": "Wagon",
  "corolla touring": "Wagon",
  wish: "Wagon",
  legacy: "Wagon",

  // Trucks / pickups
  hilux: "Truck",
  toyoace: "Truck",
  dyna: "Truck",
  titan: "Truck",
  canter: "Truck",
  condor: "Truck",
  fuso: "Truck",
  fighter: "Truck",
  navara: "Truck",
  "bt-50": "Truck",

  // Kei class (by model name; engine-size check below also catches unlisted models)
  jimny: "Kei",
  alto: "Kei",
  every: "Kei",
  copen: "Kei",
  hustler: "Kei",
  "n-box": "Kei",
  spacia: "Kei",
  carry: "Kei",
  scrum: "Kei",
  minicab: "Kei",
  sambar: "Kei",
  life: "Kei",
  vamos: "Kei",
};

// Lexus's alphanumeric model names (IS300, NX200t, RX350, LC500, ...) have too many
// trim/engine-suffix variants to enumerate individually — match by the two-letter prefix.
const LEXUS_PREFIX_BODY_TYPE: Record<string, string> = {
  is: "Sedan",
  es: "Sedan",
  gs: "Sedan",
  ls: "Sedan",
  ct: "Hatchback",
  rc: "Coupe",
  lc: "Coupe",
  rx: "SUV",
  nx: "SUV",
  ux: "SUV",
  lx: "SUV",
  gx: "SUV",
};

export function inferBodyType(model: string | null | undefined, engineCc?: number | null): string | undefined {
  if (engineCc && engineCc > 0 && engineCc <= KEI_MAX_CC) return "Kei";
  if (!model) return undefined;

  const key = model.toLowerCase().trim();
  if (BODY_TYPE_BY_MODEL[key]) return BODY_TYPE_BY_MODEL[key];

  const prefixMatch = key.match(/^([a-z]{2})\d/);
  if (prefixMatch) return LEXUS_PREFIX_BODY_TYPE[prefixMatch[1]];

  return undefined;
}
